pipeline {
    agent {
        kubernetes {
            yaml '''
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                  - name: maven
                    image: maven:3.8.4-openjdk-17
                    command:
                    - cat
                    tty: true
            '''
        }
    }
    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }

    stages {
        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                sh "echo 'Cleaned Up Workspace For Project'"
            }
        }

        stage('Code Checkout') {
            steps {
                checkout scm // This will check out the appropriate branch or PR
            }
        }

        stage('Unit Testing') {
            steps {
                sh "echo 'Running Unit Tests'"
                // Add actual unit test commands here
            }
        }

        stage('Code Analysis') {
            steps {
                sh "echo 'Running Code Analysis'"
                // Add actual code analysis commands here
            }
        }

        stage('Build Code') {
            when {
                anyOf {
                    branch 'main'
                    branch 'develop'
                }
            }
            steps {
                sh "echo 'Building Artifact'"
                // Add actual build commands here
            }
        }

        stage('Deploy to Dev') {
            when {
                branch 'develop'
            }
            steps {
                sh "echo 'Deploying to Dev Environment'"
                // Add actual deployment commands for dev here
            }
        }

        stage('Deploy to Pre-prod') {
            when {
                branch 'main'
            }
            steps {
                sh "echo 'Deploying to Pre-prod Environment'"
                // Add actual deployment commands for pre-prod here
            }
        }

        stage('PR Checks') {
            when {
                changeRequest()
            }
            steps {
                sh "echo 'Running PR Checks'"
                // Add any specific checks for PRs here
            }
        }
    }

    post {
        always {
            sh "echo 'Pipeline Completed'"
            // Add any cleanup or notification steps here
        }
    }
}
